package helpers;

public class Config {

	
	static Config config = new Config();



	public static int
		FRAME_HEIGHT = 1100,
		FRAME_WIDTH = 1400,
		FRAME_BAR_HEIGHT = 28,
		FRAME_TRACK_PADDING = 100,
		
		THREADS = 6,

		NETWORK_DISPLAY_HEIGHT = 300,
		NETWORK_DISPLAY_WIDTH = 400,
		NETWORK_DISPLAY_MARGIN = 50,
		NETWORK_DISPLAY_NODE_RADIUS = 10,

		START_POINT_SIZE = 5,
		ACTIVE_CHECKPOINTS = 15,

		POPULATION_SIZE = 600, //should be divisible by THREADS if running threaded
		GENERATIONS_PER_SIMULATION = 250,
		CYCLES_PER_GENERATION = 750,
		PER_TEST_SIMULATION_COUNT = 10,
		RANDOM_POPULATION_IN_GENERATION = (int) Math.floor(POPULATION_SIZE * 0.1),

		CAR_LENGTH = 20,
		CAR_WIDTH = 10,
		CAR_SIGHT_DISTANCE = 75,
		CAR_SIGHT_POINT_SIZE = 6,
		CAR_SIGHT_LINES_COUNT = 6,

		MAX_SPEED = 10,
		MAX_REVERSE_SPEED = 5,
		SPEED_INCREMENT = 1,
		STEER_FORCE_SIZE = 1,
		START_DIRECTION_Y = -1 * 35,
		START_DIRECTION_X = 1 * 20,
		IMAGE_BASE_ORIENTATION_X = 1,
		IMAGE_BASE_ORIENTATION_Y = 0,

		NETWORK_INPUT_LAYER_SIZE = 7,
		NETWORK_OUTPUT_LAYER_SIZE = 5,

		LOG_SPECIE_PER_X_GENERATIONS = 5
	;

	public static String
        TRACK_FILE_NAME = "setMe",
		LOG_POP_DATA_FILE_NAME = "gen.log",
		LOG_SPECIE_DATA_FILE_NAME = "species.log",
		FRAME_TITLE = "NEAT driving",
		PATH_LOG = "./results/",
		PATH_TRACKS = "./res/tracks/"
	;


	public static boolean
		DISPLAY_ALL_CHECKPOINTS = false,
		DISPLAY_ACTIVE_CHECKPOINTS = false,
		DISPLAY_WALLS = true,
		DISPLAY_ROAD = true,
		DISPLAY_START = true,
		DISPLAY_CAR = true,
		DISPLAY_CAR_SIGHT = false,
		DISPLAY_SIGHT_POINTS = false,
		DISPLAY_ONE_CAR_CHECKPOINTS = false,
		DISPLAY_FITTEST_MARK = false,

		LOG_SIM_STATE = false,
		LOG_SPECIES = false,
		LOG_INPUT_AND_ACTION = false,
		LOG_OFFSPRING_GENOME = false,
		LOG_TO_FILE = false,
		LOG_NODE_AND_CONNECTION_CREATION = false,

		RUN_THREADED = true,
		RUN_GUI = true
	;


	public static double
		MUTATION_NEW_NODE_ODDS = 0.01,
		MUTATION_NEW_CONNECTION_ODDS = 0.6,
		MUTATOIN_ADUJST_CONNECTION_ODDS = 0.9,
		MUTATION_RANDOM_CONNECTION_ODDS = 0.6,
		MUTATION_DEACTIVATE_CONNECTION_ODDS = 0.25,

		BIGGEST_CONNECTION_WEIGHT = 16.,
		SMALLEST_CONNECTION_WEIGHT = -16.,
		
		COMPATIBILITY_DISTANCE_WEIGHT_1 = 1.3,
		COMPATIBILITY_DISTANCE_WEIGHT_2 = 1.3,
		COMPATIBILITY_DISTANCE_WEIGHT_3 = 1.,
        COMPATIBILITY_THRESHOLD = 2.,
		//1, 1.5
		SHARE_FITNESS_DIST = 3.,
		SHARE_FITNESS_VALUE = 1.,
		FITTEST_MULTIPLIER = POPULATION_SIZE / 10,
		FIT_PARENT_GENE_PASS_ODDS = 0.5,
		
		SELECTION_RATIO = 0.5,
		CHANCE_TO_KILL_IF_SPECIES_ODD = 0.5
	;


}
