package helpers;

public class Config {

	
	static Config config = new Config();
	
	
	public static final int 
		FRAME_HEIGHT = 1100,
		FRAME_WIDTH = 1400,
		FRAME_BAR_HEIGHT = 28,
		FRAME_TRACK_PADDING = 50,
		
		NETWORK_DISPLAY_HEIGHT = 300,
		NETWORK_DISPLAY_WIDTH = 300,
		NETWORK_DISPLAY_MARGIN = 20,
		NETWORK_DISPLAY_NODE_RADIUS = 10,
		
		START_POINT_SIZE = 5,
		ACTIVE_CHECKPOINTS = 15,
		
		POPULATION_SIZE = 100,
		GENERATIONS_PER_SIMULATION = 10000,
		CYCLES_PER_GENERATION = 500,
		SIMULATION_COUNT = 20,
		
		CAR_LENGTH = 20,
		CAR_WIDTH = 10,
		CAR_SIGHT_DISTANCE = 75,
		CAR_SIGHT_POINT_SIZE = 6,
		CAR_SIGHT_LINES_COUNT = 6,
		
		MAX_SPEED = 10,
		MAX_REVERSE_SPEED = 5,
		SPEED_INCREMENT = 1,
		STEER_FORCE_SIZE = 1,
		START_DIRECTION_Y = -1,
		START_DIRECTION_X = 1,
		IMAGE_BASE_ORIENTATION_X = 1,
		IMAGE_BASE_ORIENTATION_Y = 0,
		
		NETWORK_INPUT_LAYER_SIZE = 7,
		NETWORK_OUTPUT_LAYER_SIZE = 5,
		
		COMPATIBILITY_THRESHOLD = 4
	;
	
	public static final String 
		TRACK_FILE_NAME = "track_1.txt",
		FRAME_TITLE = "NEAT driving"
	;
	
	
	public static final boolean
		DISPLAY_ALL_CHECKPOINTS = false,
		DISPLAY_ACTIVE_CHECKPOINTS = false,
		DISPLAY_WALLS = true,
		DISPLAY_ROAD = true,
		DISPLAY_START = true,
		DISPLAY_CAR = true,
		DISPLAY_CAR_SIGHT = false,
		DISPLAY_SIGHT_POINTS = false,
		
		
		LOG_INPUT_AND_ACTION = false
	;


	public static final double
		MUTATION_NEW_NODE_ODDS = 0.1,
		MUTATOIN_ADUJST_CONNECTION_ODDS = 0.1,
		MUTATION_RANDOM_CONNECTION_ODDS = 0.1,
		MUTATION_DEACTIVATE_CONNECTION_ODDS = 0.03,
		
		COMPATIBILITY_DISTANCE_WEIGHT_1 = 1.0,
		COMPATIBILITY_DISTANCE_WEIGHT_2 = 1.0,
		COMPATIBILITY_DISTANCE_WEIGHT_3 = 0.4
	;
	


	
			
	
}
