package helpers;

public class Config {

	
	static Config config = new Config();
	
	
	public static final int 
		FRAME_HEIGHT = 1100,
		FRAME_WIDTH = 1400,
		FRAME_BAR_HEIGHT = 28,
		FRAME_TRACK_PADDING = 50,
		
		THREADS = 4,
		
		NETWORK_DISPLAY_HEIGHT = 300,
		NETWORK_DISPLAY_WIDTH = 300,
		NETWORK_DISPLAY_MARGIN = 20,
		NETWORK_DISPLAY_NODE_RADIUS = 10,
		
		START_POINT_SIZE = 5,
		ACTIVE_CHECKPOINTS = 15,
		
		POPULATION_SIZE = 500,
		GENERATIONS_PER_SIMULATION = 200,
		CYCLES_PER_GENERATION = 750,
		SIMULATION_COUNT = 20,
		
		CAR_LENGTH = 20,
		CAR_WIDTH = 10,
		CAR_SIGHT_DISTANCE = 75,
		CAR_SIGHT_POINT_SIZE = 6,
		CAR_SIGHT_LINES_COUNT = 6,
		
		MAX_SPEED = 10,
		MAX_REVERSE_SPEED = 5,
		SPEED_INCREMENT = 1,
		STEER_FORCE_SIZE = 1,
		START_DIRECTION_Y = -1,
		START_DIRECTION_X = 1,
		IMAGE_BASE_ORIENTATION_X = 1,
		IMAGE_BASE_ORIENTATION_Y = 0,
		
		NETWORK_INPUT_LAYER_SIZE = 7,
		NETWORK_OUTPUT_LAYER_SIZE = 5,
		
		LOG_SPECIE_PER_X_GENERATIONS = 5
	;
	
	public static final String 
		TRACK_FILE_NAME = "track_2.txt",
		LOG_POP_DATA_FILE_NAME = "log.log",
		LOG_SPECIE_DATA_FILE_NAME = "species.log",
		FRAME_TITLE = "NEAT driving"
	;
	
	
	public static final boolean
		DISPLAY_ALL_CHECKPOINTS = false,
		DISPLAY_ACTIVE_CHECKPOINTS = false,
		DISPLAY_WALLS = true,
		DISPLAY_ROAD = true,
		DISPLAY_START = true,
		DISPLAY_CAR = true,
		DISPLAY_CAR_SIGHT = false,
		DISPLAY_SIGHT_POINTS = false,
		DISPLAY_ONE_CAR_CHECKPOINTS = true,
		
		LOG_SIM_STATE = true,
		LOG_SPECIES = true,
		LOG_INPUT_AND_ACTION = false,
		LOG_OFFSPRING_GENOME = false,
		LOG_TO_FILE = true,
		
		RUN_THREADED = true,
		RUN_GUI = true
	;


	public static final double
		MUTATION_NEW_NODE_ODDS = 0.05,
		MUTATION_NEW_CONNECTION_ODDS = 0.1,
		MUTATOIN_ADUJST_CONNECTION_ODDS = 0.4,
		MUTATION_RANDOM_CONNECTION_ODDS = 0.3,
		MUTATION_DEACTIVATE_CONNECTION_ODDS = 0.1,
		
		COMPATIBILITY_DISTANCE_WEIGHT_1 = 1.0,
		COMPATIBILITY_DISTANCE_WEIGHT_2 = 1.0,
		COMPATIBILITY_DISTANCE_WEIGHT_3 = 1.5,
		
		COMPATIBILITY_THRESHOLD = 2.5,
		SHARE_FITNESS_VALUE = 2.7,
		
		SELECTION_RATIO = 0.5,
		CHANCE_TO_KILL_IF_SPECIES_ODD = 0.3
	;
	


	
			
	
}
